// <auto-generated />
using System;
using FightClub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FightClub.Infrastructure.Migrations
{
    [DbContext(typeof(FightClubDbContext))]
    partial class FightClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FightClub.Domain.Entities.Boxer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Boxers");
                });

            modelBuilder.Entity("FightClub.Domain.Entities.Fight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxerAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxerBId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FightDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlannedRounds")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("FightClub.Domain.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("FightClub.Domain.Entities.Boxer", b =>
                {
                    b.OwnsOne("FightClub.Domain.ValueObjects.BoxerRanking", "Ranking", b1 =>
                        {
                            b1.Property<Guid>("BoxerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EloRating")
                                .HasColumnType("integer");

                            b1.Property<int>("RankingPoints")
                                .HasColumnType("integer");

                            b1.HasKey("BoxerId");

                            b1.ToTable("Boxers");

                            b1.WithOwner()
                                .HasForeignKey("BoxerId");
                        });

                    b.OwnsOne("FightClub.Domain.ValueObjects.BoxerStatistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("BoxerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BestWinStreak")
                                .HasColumnType("integer");

                            b1.Property<int>("Draws")
                                .HasColumnType("integer");

                            b1.Property<int>("KnockoutLosses")
                                .HasColumnType("integer");

                            b1.Property<int>("Knockouts")
                                .HasColumnType("integer");

                            b1.Property<DateTime?>("LastFightDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Losses")
                                .HasColumnType("integer");

                            b1.Property<int>("TechnicalKnockoutLosses")
                                .HasColumnType("integer");

                            b1.Property<int>("TechnicalKnockouts")
                                .HasColumnType("integer");

                            b1.Property<int>("WinStreak")
                                .HasColumnType("integer");

                            b1.Property<int>("Wins")
                                .HasColumnType("integer");

                            b1.HasKey("BoxerId");

                            b1.ToTable("Boxers");

                            b1.WithOwner()
                                .HasForeignKey("BoxerId");
                        });

                    b.Navigation("Ranking")
                        .IsRequired();

                    b.Navigation("Statistics")
                        .IsRequired();
                });

            modelBuilder.Entity("FightClub.Domain.Entities.Fight", b =>
                {
                    b.OwnsMany("FightClub.Domain.Entities.FightRound", "Rounds", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("FightId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsFinished")
                                .HasColumnType("boolean");

                            b1.Property<int>("Number")
                                .HasColumnType("integer");

                            b1.Property<int>("ScoreA")
                                .HasColumnType("integer");

                            b1.Property<int>("ScoreB")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("FightId");

                            b1.ToTable("FightRound");

                            b1.WithOwner()
                                .HasForeignKey("FightId");

                            b1.OwnsMany("FightClub.Domain.Entities.RoundEvent", "Events", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("BoxerId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("FightRoundId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("OccurredAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("FightRoundId");

                                    b2.ToTable("RoundEvent");

                                    b2.WithOwner()
                                        .HasForeignKey("FightRoundId");
                                });

                            b1.Navigation("Events");
                        });

                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
