// <auto-generated />
using System;
using FightClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FightClub.Migrations
{
    [DbContext(typeof(FightClubDbContext))]
    [Migration("20260628211025_AddBoxerStatistics")]
    partial class AddBoxerStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FightClub.Entities.Boxer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeightCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Boxers");
                });

            modelBuilder.Entity("FightClub.Entities.Fight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxerAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoxerBId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FightDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultMethod")
                        .HasColumnType("text");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BoxerAId");

                    b.HasIndex("BoxerBId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FightClub.Entities.Trainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("FightClub.Entities.Boxer", b =>
                {
                    b.HasOne("FightClub.Entities.Trainer", "Trainer")
                        .WithMany("Boxers")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FightClub.Entities.Fight", b =>
                {
                    b.HasOne("FightClub.Entities.Boxer", "BoxerA")
                        .WithMany("FightsAsA")
                        .HasForeignKey("BoxerAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FightClub.Entities.Boxer", "BoxerB")
                        .WithMany("FightsAsB")
                        .HasForeignKey("BoxerBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FightClub.Entities.Boxer", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BoxerA");

                    b.Navigation("BoxerB");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("FightClub.Entities.Boxer", b =>
                {
                    b.Navigation("FightsAsA");

                    b.Navigation("FightsAsB");
                });

            modelBuilder.Entity("FightClub.Entities.Trainer", b =>
                {
                    b.Navigation("Boxers");
                });
#pragma warning restore 612, 618
        }
    }
}
