// <auto-generated />
using FightClub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FightClub.Infrastructure.Persistence.Migrations;

[DbContext(typeof(FightClubDbContext))]
partial class FightClubDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.9")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FightClub.Entities.Boxer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Age")
                    .HasColumnType("integer");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Draws")
                    .HasColumnType("integer");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<int>("Losses")
                    .HasColumnType("integer");

                b.Property<Guid>("TrainerId")
                    .HasColumnType("uuid");

                b.Property<string>("WeightCategory")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("character varying(30)");

                b.Property<int>("Wins")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("TrainerId");

                b.ToTable("Boxers");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.Fight", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("BoxerAId")
                    .HasColumnType("uuid");

                b.Property<Guid>("BoxerBId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("BoxerId")
                    .HasColumnType("uuid");

                b.Property<Guid?>("BoxerId1")
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("PlannedRounds")
                    .HasColumnType("integer");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<Guid?>("WinnerId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("BoxerAId");

                b.HasIndex("BoxerBId");

                b.HasIndex("BoxerId");

                b.HasIndex("BoxerId1");

                b.ToTable("Fights");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.FightRound", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<Guid>("FightId")
                    .HasColumnType("uuid");

                b.Property<int>("Number")
                    .HasColumnType("integer");

                b.Property<int>("Result")
                    .HasColumnType("integer");

                b.Property<int>("ScoreA")
                    .HasColumnType("integer");

                b.Property<int>("ScoreB")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("FightId");

                b.ToTable("FightRound");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.RoundEvent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("FightRoundId")
                    .HasColumnType("uuid");

                b.Property<int>("Impact")
                    .HasColumnType("integer");

                b.Property<Guid?>("SourceBoxerId")
                    .HasColumnType("uuid");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("FightRoundId");

                b.ToTable("RoundEvent");
            });

        modelBuilder.Entity("FightClub.Entities.Trainer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Age")
                    .HasColumnType("integer");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.ToTable("Trainers");
            });

        modelBuilder.Entity("FightClub.Entities.Boxer", b =>
            {
                b.HasOne("FightClub.Entities.Trainer", "Trainer")
                    .WithMany("Boxers")
                    .HasForeignKey("TrainerId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .IsRequired();

                b.Navigation("Trainer");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.Fight", b =>
            {
                b.HasOne("FightClub.Entities.Boxer", "BoxerA")
                    .WithMany()
                    .HasForeignKey("BoxerAId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("FightClub.Entities.Boxer", "BoxerB")
                    .WithMany()
                    .HasForeignKey("BoxerBId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("FightClub.Entities.Boxer", null)
                    .WithMany("FightsAsA")
                    .HasForeignKey("BoxerId");

                b.HasOne("FightClub.Entities.Boxer", null)
                    .WithMany("FightsAsB")
                    .HasForeignKey("BoxerId1");

                b.Navigation("BoxerA");

                b.Navigation("BoxerB");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.FightRound", b =>
            {
                b.HasOne("FightClub.Entities.Fight.Fight", "Fight")
                    .WithMany("Rounds")
                    .HasForeignKey("FightId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Fight");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.RoundEvent", b =>
            {
                b.HasOne("FightClub.Entities.Fight.FightRound", "FightRound")
                    .WithMany("Events")
                    .HasForeignKey("FightRoundId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("FightRound");
            });

        modelBuilder.Entity("FightClub.Entities.Boxer", b =>
            {
                b.Navigation("FightsAsA");

                b.Navigation("FightsAsB");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.Fight", b =>
            {
                b.Navigation("Rounds");
            });

        modelBuilder.Entity("FightClub.Entities.Fight.FightRound", b =>
            {
                b.Navigation("Events");
            });

        modelBuilder.Entity("FightClub.Entities.Trainer", b =>
            {
                b.Navigation("Boxers");
            });
#pragma warning restore 612, 618
    }
}
